name: 'Upload to S3 using AWS CLI'
description: 'Upload files or directories to an S3 bucket using the AWS CLI.'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  s3-bucket:
    description: 'S3 Bucket Name'
    required: true
  local-path:
    description: 'Local path to the file or directory to upload'
    required: true
  s3-key:
    description: 'S3 key (path) where the file/directory should be uploaded'
    required: true
  zip-before-upload:
    description: 'Whether to zip the directory before uploading. Set to `true` or `false`.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS CLI
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_DEFAULT_REGION

    - name: Upload to S3
      shell: bash
      run: |
        if [[ "${{ inputs.zip-before-upload }}" == "true" ]]; then
          echo "Zipping input file or directory before upload..."
          zip -r upload.zip "${{ inputs.local-path }}"
          aws s3 cp upload.zip "s3://${{ inputs.s3-bucket }}/${{ inputs.s3-key }}"
          rm -f upload.zip
        else
          echo "Uploading file or directory..."
          aws s3 cp "${{ inputs.local-path }}" "s3://${{ inputs.s3-bucket }}/${{ inputs.s3-key }}"
        fi
